backend:
  name: github
  branch: main 
  repo: jfelding/jacob-experiments-astro-site
  site_domain: jacob-experiments.com 
  base_url: https://jacob-experiments-astro-site.pages.dev/ 
  auth_endpoint: oauth 

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Time Investment Rating", name: "timeInvestmentRating", widget: "string" }
      - { label: "Necessity Rating", name: "necessityRating", widget: "string" }
      - { label: "Status Rating", name: "statusRating", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }

  - name: "Ideas"
    label: "Ideas"
    folder: "src/content/ideas"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { category: "Categories", name: "categories", widget: "list" }  

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media